### ISSUE TITLE
Fix upcoming PropTypes warning

### ISSUE THREAD

**Issue by gaearon** [react-bootstrap/react-prop-types#25]
This library will start emitting warnings with React 15.3.0.
Please fix it according to the guide:

https://github.com/facebook/react/blob/f9940415392a6187374cdad69022bfc9e2a392a3/docs/warnings/dont-call-proptypes.md#fixing-the-false-positive-in-third-party-proptypes

Thank you!

**Comment by taion** [comment]
We're still not done updating things for 15.2 yet ;_;

**Comment by dozoisch** [comment]
@taion good thing is that the example in the react doc fixes it for us :-p

**Comment by taion** [comment]
@gaearon Can you update the post https://facebook.github.io/react/warnings/dont-call-proptypes.html to note that it applies to a previous version of this library? We've since closed this issue.

**Comment by jquense** [comment]
ditto @taion we get enough "trying to be helpful, unhelpful" issues, without folks complaining that our library is broken because the official React warning calls it out specifically

**Comment by gaearon** [comment]
Ugh, I never expected people would do that. 
Can you send a PR? I'm on a vacation now but somebody else can merge it.

**Comment by jquense** [comment]
sure, thanks!
