### ISSUE TITLE
This library is currently an example in official documentation of how not to do propType validation

### ISSUE THREAD

**Issue by adamsinnett** [react-bootstrap/react-prop-types#27]
See https://facebook.github.io/react/warnings/dont-call-proptypes.html.

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-prop-types/blob/master/CHANGELOG.md#v040

**Comment by jquense** [comment]
no it's not you are misunderstanding the issue there.

there is literally a whole section about this: https://facebook.github.io/react/warnings/dont-call-proptypes.html#fixing-the-false-positive-in-third-party-proptypes
