### ISSUE TITLE
Warnings about requirements for assistive technologies.

### ISSUE THREAD

**Issue by villesau** [react-bootstrap/react-prop-types#28]
See the issue in react bootstrap repo: https://github.com/react-bootstrap/react-bootstrap/issues/1426

There was a suggestion to open an issue here instead.

Proptypes are used for required props. As id is not required, components shouldn't warn about those. It's imo pretty simple. It's easy to end up to ignore valid errors when there is unnecessary errors from bootstrap.

**Comment by jquense** [comment]
hi there, this library provides propTypes its not the right place e to discuss whether they are being used  in an appropriate way.  that bootstrap issue already covers the topic pretty extensively
