### ISSUE TITLE
Can this be used outside of react-land?

### ISSUE THREAD

**Issue by ZeeCoder** [react-bootstrap/react-prop-types#29]
After using propTypes in React, I wanted to have the same typechecking ability for non-react code.
I found this so far: https://www.npmjs.com/package/type-check

But I'd rather use the React propTypes solution if it's possible to do so.

**Comment by jquense** [comment]
it _can_ be but it has a peer depedency on React so its a lot of extra weight. I might recommend a more robust solution tho. like https://github.com/gcanti/tcomb for a general purpose approach

**Comment by ZeeCoder** [comment]
Thanks a lot!
