### ISSUE TITLE
Enable TravisCI

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-prop-types#3]
(coveralls.io I've already setup)

Somebody with admin rights in `react-bootstrap` organization,
enable please TravisCI for this project here https://travis-ci.org/profile/react-bootstrap
:cherries: 

That's what I see
<img width="503" alt="screen shot 2015-07-03 at 7 56 32 pm" src="https://cloud.githubusercontent.com/assets/847572/8502778/ce998272-21bd-11e5-8090-8aa0d9c7c0bc.png">

**Comment by mtscout6** [comment]
I just enabled it on travis so it should be good to go now.
