### ISSUE TITLE
Transfering package name

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-prop-types#30]
ping: @react-bootstrap/collaborators especially @AlexKVal who wrote the original code here. 

The React team has been working towards splitting PropTypes out of react core and would like to use the name `react-prop-types` (for obvious reasons). I didn't personally see a problem with giving up the name but would like folks to weigh in if they do!

@acdlite said they'd help make sure we don't run into any issues (major version bump, a comment noting where the original went, etc) So from a technical prospective there shouldn't be any issues with packages that depend on this, except that to upgrade it we'll need to point to the new package. 

Thoughts? concerns?

**Comment by taion** [comment]
i noted already that i was fine with this

**Comment by taion** [comment]
i really wish that `all` and `componentOrElement` could be upstreamed though

**Comment by jquense** [comment]
ME TOO (also elementType). I suggested to @acdlite that we'd be open helping offset the added maintenance burden if they wanted to do that (the code is well tested used ;) )

**Comment by mtscout6** [comment]
I am also behind this 100%

**Comment by mathieumg** [comment]
No problem with it! :+1:

**Comment by kevinzwhuang** [comment]
Sounds good to me. 👍

**Comment by dozoisch** [comment]
👍 No problem with it

**Comment by AlexKVal** [comment]
Sure yes 👍

**Comment by acdlite** [comment]
Regarding upstreaming some of the new validators, I don't think we're totally opposed to adding new ones, but they'd have to go through the usual React PR process. Most of these wouldn't work as-is. E.g. `componentOrElement` probably wouldn't be accepted because we don't want to encourage `findDOMNode` usage, or passing component instances as props.

**Comment by acdlite** [comment]
Glad you support transferring the package! It's much appreciated :)

**Comment by acdlite** [comment]
Any update on this?

**Comment by mathieumg** [comment]
@acdlite Not sure what update there needs to be, it seems pretty unanimous everyone agrees with the transfer. Can we help further in any way? Thank you!

**Comment by acdlite** [comment]
```
npm owner add acdlite react-prop-types
```

**Comment by mathieumg** [comment]
I'm pretty sure I don't have the npm rights at the moment, but @jquense and @taion for sure do.

**Comment by jquense** [comment]
_finnnnnally_ done

new repo here for this code: https://github.com/react-bootstrap/prop-types-extra
